### 1. Iterator 

In [11]:
import numpy as np
a=np.arange(0,60,5)
print(a)
a=a.reshape(3,4)
print(a)
b=np.arange(0,24,6)
print(b)
b=b.reshape(1,4)
for x,y in np.nditer([a,b]):
    print(x,y)


[ 0  5 10 15 20 25 30 35 40 45 50 55]
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[ 0  6 12 18]
0 0
5 6
10 12
15 18
20 0
25 6
30 12
35 18
40 0
45 6
50 12
55 18


### 2. Change shape/size 

In [17]:
a=np.arange(0,60,5)
print(a)
a=a.reshape(3,4)
print(a)

print(list(a.flat))
print(a.flatten(order='F'))
print(a.flatten(order='C'))
print(a.flatten(order='A'))
print(a.flatten(order='k'))

[ 0  5 10 15 20 25 30 35 40 45 50 55]
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55]
[ 0 20 40  5 25 45 10 30 50 15 35 55]
[ 0  5 10 15 20 25 30 35 40 45 50 55]
[ 0  5 10 15 20 25 30 35 40 45 50 55]
[ 0  5 10 15 20 25 30 35 40 45 50 55]


### 3.Transpose

In [48]:
a=np.arange(24).reshape(2,3,4)
print(a)

# use transpose function
b=np.transpose(a)
print(b)
print(b.shape)
c=np.transpose(a,(1,0,2))
print(c)
print(c.shape)

# use .T method
print(c.T)
print(c.T.shape)

# use swapaxes function, swap 2 axes
d=np.swapaxes(a,2,0)
print(d)
print(d.shape)

# use rollaxis function, apply to 1 axis only 
e=np.rollaxis(a,1,3)
print(e)
print(e.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
(4, 3, 2)
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
(3, 2, 4)
[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]
(4, 2, 3)
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
(4, 3, 2)
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]
(2, 4, 3)


### 4. dimension revision 

In [74]:
a=np.arange(6).reshape(1,6)
print(a)
a1=np.arange(6).reshape(2,3)
print(a1)

# broadcast_to 
b=np.broadcast_to(a,(2,6))
print(b)

#expand_dims
c1=np.expand_dims(a1, axis=0)
print("c1:",'\n',c1,'\n', c1.shape)
c2=np.expand_dims(a1, axis=1)
print('c2:','\n',c2,'\n',c2.shape)
c3=np.expand_dims(a1, axis=2)
print('c3:','\n',c3,'\n',c3.shape)

#squeeze
d1=np.squeeze(c1,0)
print('d1:','\n',d1,'\n', d1.shape)
d2=np.squeeze(c2,1)
print('d2:','\n',d2,'\n', d2.shape)
d3=np.squeeze(c3,2)
print('d3:','\n',d3,'\n', d3.shape)

[[0 1 2 3 4 5]]
[[0 1 2]
 [3 4 5]]
[[0 1 2 3 4 5]
 [0 1 2 3 4 5]]
c1: 
 [[[0 1 2]
  [3 4 5]]] 
 (1, 2, 3)
c2: 
 [[[0 1 2]]

 [[3 4 5]]] 
 (2, 1, 3)
c3: 
 [[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] 
 (2, 3, 1)
d1: 
 [[0 1 2]
 [3 4 5]] 
 (2, 3)
d2: 
 [[0 1 2]
 [3 4 5]] 
 (2, 3)
d3: 
 [[0 1 2]
 [3 4 5]] 
 (2, 3)


### 5.  concatenate

In [85]:
a1=np.arange(4,8).reshape(2,2)
a2=np.arange(0,4).reshape(2,2)
print('a1=',a1,'\n','a2=',a2)

## concatenate 
b1=np.concatenate((a1,a2),axis=0)
print('b1=','\n',b1,'\n','shape=',b1.shape)
b2=np.concatenate((a1,a2),axis=1)
print('b2=','\n',b2,'\n','shape=',b2.shape)

## stack
c1=np.stack((a1,a2),0)
print('c1=','\n',c1,'\n','shape=',c1.shape)
c2=np.stack((a1,a2),1)
print('c2=','\n',c2,'\n','shape=',c2.shape)

## hstack
d1=np.hstack((a1,a2))
print('d1=','\n',d1,'\n','shape=',d1.shape)

## vstack
e1=np.vstack((a1,a2))
print('e1=','\n',e1,'\n','shape=',e1.shape)

a1= [[4 5]
 [6 7]] 
 a2= [[0 1]
 [2 3]]
b1= 
 [[4 5]
 [6 7]
 [0 1]
 [2 3]] 
 shape= (4, 2)
b2= 
 [[4 5 0 1]
 [6 7 2 3]] 
 shape= (2, 4)
c1= 
 [[[4 5]
  [6 7]]

 [[0 1]
  [2 3]]] 
 shape= (2, 2, 2)
c2= 
 [[[4 5]
  [0 1]]

 [[6 7]
  [2 3]]] 
 shape= (2, 2, 2)
d1= 
 [[4 5 0 1]
 [6 7 2 3]] 
 shape= (2, 4)
e1= 
 [[4 5]
 [6 7]
 [0 1]
 [2 3]] 
 shape= (4, 2)


### 6. split

In [97]:
a1=np.arange(6).reshape(2,3)
print('a1=',a1,'\n','shape=',a1.shape)

### split 
b1=np.split(a1,2,axis=0)
print('b1=',b1,'\n')
b2=np.split(a1,3,axis=1)
print('b2=',b2,'\n')

### hsplit 
c1=np.hsplit(a1,3)
print('c1=',c1,'\n')

### vsplit
d1=np.vsplit(a1,2)
print('d1=',d1,'\n')

a1= [[0 1 2]
 [3 4 5]] 
 shape= (2, 3)
b1= [array([[0, 1, 2]]), array([[3, 4, 5]])] 

b2= [array([[0],
       [3]]), array([[1],
       [4]]), array([[2],
       [5]])] 

c1= [array([[0],
       [3]]), array([[1],
       [4]]), array([[2],
       [5]])] 

d1= [array([[0, 1, 2]]), array([[3, 4, 5]])] 



### 7. element wise operations

In [112]:
a1=np.arange(6).reshape(2,3)
print('a1=',a1,'\n','shape=',a1.shape)
a2=[1,1,1,2,2,3,4,5,6,6,7,8,9,10]
indice=np.arange(len(a2))
print('a2=',a2,'\n','indice=',indice)

# resize
b1=np.resize(a1,(3,2))
print('b1=',b1,'\n','shape=',b1.shape)
b2=np.resize(a1,(3,3))
print('b2=',b2,'\n','shape=',b2.shape)
b3=np.resize(a1,(2,2))
print('b3=',b3,'\n','shape=',b3.shape)

#append 
c1=np.append(a1,[[98,99,100]],axis=0)
print('c1=',c1,'\n','shape=',c1.shape)
c2=np.append(a1,[[98],[99]],axis=1)
print('c2=',c2,'\n','shape=',c2.shape)

#insert 
d1=np.insert(a1,1,[98,99,100],axis=0)
print('d1=',d1,'\n','shape=',d1.shape)
d2=np.insert(a1,1,[98,99],axis=1)
print('d2=',d2,'\n','shape=',d2.shape)

#delete
e1=np.delete(a1,5)
print('e1=',e1,'\n','shape=',e1.shape)
e2=np.delete(a1,1,axis=0)
print('e2=',e2,'\n','shape=',e2.shape)
e3=np.delete(a1,2,axis=1)
print('e3=',e3,'\n','shape=',e3.shape)

#unique 
f1=np.unique(a2)
print('f1=',f1)
f2,indice2=np.unique(a2,return_index=True)
print('f2=',f2,'\n','indice2=',indice2)
f3,indice3=np.unique(a2,return_inverse=True)
print('f3=',f3,'\n','indice3=',indice3)
f4,indice4=np.unique(a2,return_counts=True)
print('f4=',f4,'\n','indice4=',indice4)


a1= [[0 1 2]
 [3 4 5]] 
 shape= (2, 3)
a2= [1, 1, 1, 2, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10] 
 indice= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
b1= [[0 1]
 [2 3]
 [4 5]] 
 shape= (3, 2)
b2= [[0 1 2]
 [3 4 5]
 [0 1 2]] 
 shape= (3, 3)
b3= [[0 1]
 [2 3]] 
 shape= (2, 2)
c1= [[  0   1   2]
 [  3   4   5]
 [ 98  99 100]] 
 shape= (3, 3)
c2= [[ 0  1  2 98]
 [ 3  4  5 99]] 
 shape= (2, 4)
d1= [[  0   1   2]
 [ 98  99 100]
 [  3   4   5]] 
 shape= (3, 3)
d2= [[ 0 98  1  2]
 [ 3 99  4  5]] 
 shape= (2, 4)
e1= [0 1 2 3 4] 
 shape= (5,)
e2= [[0 1 2]] 
 shape= (1, 3)
e3= [[0 1]
 [3 4]] 
 shape= (2, 2)
f1= [ 1  2  3  4  5  6  7  8  9 10]
f2= [ 1  2  3  4  5  6  7  8  9 10] 
 indice2= [ 0  3  5  6  7  8 10 11 12 13]
f3= [ 1  2  3  4  5  6  7  8  9 10] 
 indice3= [0 0 0 1 1 2 3 4 5 5 6 7 8 9]
f4= [ 1  2  3  4  5  6  7  8  9 10] 
 indice4= [3 2 1 1 1 2 1 1 1 1]


### 8. Strings 

In [120]:
w1=['Hello,world!']
w2=['this is a test.']
a=np.char.encode('hello','cp500')

print('add:',np.char.add(w1,w2))
print('multiply: ',np.char.multiply(w1,3))
print('center: ',np.char.center('Hello!', 20, fillchar='*'))
print('capitalize: ',np.char.capitalize(w2))
print('title: ',np.char.title(w2))
print('lower: ', np.char.lower('HELLO'))
print('upper: ',np.char.upper('hello'))
print('split: ',np.char.split(w1, sep=','))
print('splitlines: ', np.char.splitlines('hello\nworld'))
print('strip: ',np.char.strip(['apple','admin','blue'],'a'))
print('join: ', np.char.join([":",'-'],['dmy','gtwer']))
print('replace: ',np.char.replace('AppleTree','e','*'))
print('encode: ',np.char.encode('hello','cp500'))
print('decode: ',np.char.decode(a,'cp500'))



add: ['Hello,world!this is a test.']
multiply:  ['Hello,world!Hello,world!Hello,world!']
center:  *******Hello!*******
capitalize:  ['This is a test.']
title:  ['This Is A Test.']
lower:  hello
upper:  HELLO
split:  [list(['Hello', 'world!'])]
splitlines:  ['hello', 'world']
strip:  ['pple' 'dmin' 'blue']
join:  ['d:m:y' 'g-t-w-e-r']
replace:  Appl*Tr**
encode:  b'\x88\x85\x93\x93\x96'
decode:  hello


### 9. Arithmetic 

In [125]:
a=np.arange(0,180,30)
print(a)
b=np.array([1.0,5,55,123,0.567,25,5321])
print(b)
c=np.array([0.25,1,2,0.2,100])
print(c)
d=np.array([[3,7,5],[8,4,3],[2,4,9]])
print(d)

#trignometric
print('sin',np.sin(a*np.pi/180))
print('cos',np.cos(a*np.pi/180))
print('tan',np.tan(a*np.pi/180))

#decimal places
print('around',np.around(b))
print('around',np.around(b, decimals=2))
print('floor',np.floor(b))
print('ceil',np.ceil(b))

#arithmetic
print('reciprocal',np.reciprocal(c))
print('power',np.power(c,2))
print('mod',np.mod([1,5,8,20],[2,3,4,5]))

#statistical
print('amin',np.amin(d,axis=1))
print('amax',np.amax(d,axis=0))
print('ptp',np.ptp(d))
print('percentile',np.percentile(d,50))
print('median',np.median(d))
print('mean',np.mean(d))
print('average',np.average(d))
print('std',np.std(b))
print('var',np.var(b))


[  0  30  60  90 120 150]
[1.000e+00 5.000e+00 5.500e+01 1.230e+02 5.670e-01 2.500e+01 5.321e+03]
[  0.25   1.     2.     0.2  100.  ]
[[3 7 5]
 [8 4 3]
 [2 4 9]]
sin [0.        0.5       0.8660254 1.        0.8660254 0.5      ]
cos [ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01]
tan [ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01]
around [1.000e+00 5.000e+00 5.500e+01 1.230e+02 1.000e+00 2.500e+01 5.321e+03]
around [1.000e+00 5.000e+00 5.500e+01 1.230e+02 5.700e-01 2.500e+01 5.321e+03]
floor [1.000e+00 5.000e+00 5.500e+01 1.230e+02 0.000e+00 2.500e+01 5.321e+03]
ceil [1.000e+00 5.000e+00 5.500e+01 1.230e+02 1.000e+00 2.500e+01 5.321e+03]
reciprocal [4.   1.   0.5  5.   0.01]
power [6.25e-02 1.00e+00 4.00e+00 4.00e-02 1.00e+04]
mod [1 2 0 0]
amin [3 3 2]
amax [8 7 9]
ptp 7
percentile 4.0
median 4.0
mean 5.0
average 5.0
std 1850.183404637111
var 3423178.6307945712


### 10. Sort, search and count 

In [126]:
a=np.array([[3,7,5,1,2],[8,4,3,-5,9],[2,4,9,0,3]])
nm=['rawer','wqrfsdf','hjwerty']
dv=['f.y.','s.t.','f.y.']
            
print('sort:', np.sort(a))
print('argsort:',np.argsort(a))
print('argmax:',np.argmax(a))
print('argmin:',np.argmin(a))
print('nonzero:',np.nonzero(a))
print('where:',np.where(a<3))
print('lexsort:',np.lexsort((dv,nm)))


        

sort: [[ 1  2  3  5  7]
 [-5  3  4  8  9]
 [ 0  2  3  4  9]]
argsort: [[3 4 0 2 1]
 [3 2 1 0 4]
 [3 0 4 1 2]]
argmax: 9
argmin: 8
nonzero: (array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 4], dtype=int64))
where: (array([0, 0, 1, 2, 2], dtype=int64), array([3, 4, 3, 0, 3], dtype=int64))
lexsort: [2 0 1]
